
# Machine Learning Zoomcamp

### Introduction to Numpy

Plan:
 * Creating Arrays
 * Multi-dimensional Arrays
 * Randomly generated arrays
 * Elementwise operations
    * Comparison Operations
    * Logical operations
 * Summarizing operations

## NumPy quickstart

Numpy main object is the homogeneous multi-dimensional array. It is a table of elements mainly numbers all of th same type and indexed by a tuple of non-negative numbers.
**Dimensions**- in numpy dimensions are known as axes
# Understanding Dimensions in Python Arrays

## 1. Introduction to Array Dimensions

In Python, array dimensions refer to the number of axes (or levels of depth) in an array structure. Understanding dimensions is crucial for working with data in scientific computing, machine learning, and data analysis.

## 2. One-Dimensional Arrays (1D)

- Represent a single list of elements
- Have one axis
- Example: `[1, 2, 3, 4, 5]`
- Shape: `(n,)` where `n` is the number of elements

## 3. Two-Dimensional Arrays (2D)

- Represent a table of elements (rows and columns)
- Have two axes
- Example:
  ```python
  [[1, 2, 3],
   [4, 5, 6]]
  ```
- Shape: `(m, n)` where `m` is the number of rows and `n` is the number of columns

## 4. Three-Dimensional Arrays (3D)

- Represent a cube of elements (stacked 2D arrays)
- Have three axes
- Example:
  ```python
  [[[1, 2], [3, 4]],
   [[5, 6], [7, 8]]]
  ```
- Shape: `(l, m, n)` where `l` is the number of 2D arrays, `m` is the number of rows, and `n` is the number of columns


In [2]:
#Getting the dimensions of an array
import numpy as np
import matplotlib.pyplot as plt

In [4]:
oned_arr = np.array([1,2,3])
twod_arr= np.array([[1, 2, 3],
                  [4, 5, 6]])
threed_arr=np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

ndim will output the number of axes (dimensions) of the array.

In [6]:
#ndim method in numpy
oned_arr.ndim

1

In [7]:
twod_arr.ndim

2

In [8]:
threed_arr.ndim

3

### ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

In [10]:
print(oned_arr.shape)
print(twod_arr.shape)
print(threed_arr.shape)

(3,)
(2, 3)
(2, 2, 2)


### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

In [11]:
print(oned_arr.size)
print(twod_arr.size)
print(threed_arr.size)

3
6
8


### ndarray.dtype
an object describing the type of the elements in the array. 

In [13]:
print(oned_arr.dtype)
print(twod_arr.dtype)
print(threed_arr.dtype)

int64
int64
int64


In [14]:
type(oned_arr)

numpy.ndarray

In [17]:
#Creation of arrays
sample_1 = np.arange(6).reshape(2,3)
print(sample_1)

[[0 1 2]
 [3 4 5]]


In [18]:
sample_2 = np.arange(36).reshape(3,4,3)
print(sample_2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


### Basic Arithmetic operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [21]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)


[20 30 40 50]
[0 1 2 3]


In [22]:
c = a - b
print(c)


[20 29 38 47]


In [24]:
print(b**2)


[0 1 4 9]


In [26]:
print(10 * np.sin(a))
print(a < 35)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [29]:

A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])

In [30]:
# * operator
print(A*B)

[[2 0]
 [0 4]]


In [31]:
print(A@B)

[[5 4]
 [3 4]]


In [32]:
print(A.dot(B))

[[5 4]
 [3 4]]


In [34]:
print(np.dot(A,B))

[[5 4]
 [3 4]]


In [35]:
# Summing all the elements of an array
A.sum()

np.int64(3)

In [36]:
B.sum()

np.int64(9)

In [37]:
A.min()

np.int64(0)

In [38]:
B.min()

np.int64(0)

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [39]:
b = np.arange(12).reshape(3, 4)

In [40]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
print(b[0:3,:2])

[[0 1]
 [4 5]
 [8 9]]


In [51]:
#Applying sum on a certain dimension
print(b.sum(axis=0))

[12 15 18 21]
